# Generated by Django 4.2.16 on 2026-05-29 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('face_descriptor', models.JSONField(blank=True, null=True)),
                ('daily_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_absent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='atestados/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='timeclock.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PunchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('clock_in', 'Entrada'), ('lunch_start', 'Início Almoço'), ('lunch_end', 'Fim Almoço'), ('clock_out', 'Saída')], max_length=20)),
                ('punched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_manual', models.BooleanField(default=False)),
                ('manual_reason', models.CharField(blank=True, max_length=255)),
                ('face_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='timeclock.employee')),
            ],
            options={
                'ordering': ['punched_at'],
                'indexes': [models.Index(fields=['employee', 'punched_at'], name='timeclock_p_employe_e64abe_idx')],
            },
        ),
    ]
